import request from '../utils/request'

export const getClubs = (params={page:1,size:100}) => request.get('/clubs', { params })
export const getUserClubDetail = (clubId) => request.get(`/user/clubs/${clubId}`)

export const getClubProfile = () => request.get('/club/profile')
export const updateClubProfile = (data) => request.put('/club/profile', data)
export const getClubPlayers = () => request.get('/club/players')
export const createClubPlayer = (data) => request.post('/club/players', data)
export const updateClubPlayer = (id, data) => request.put(`/club/players/${id}`, data)
export const updateClubPlayerStatus = (id, playerStatus) => request.put(`/club/players/${id}/status`, { playerStatus })
export const getClubCoaches = () => request.get('/club/coaches')
export const createClubCoach = (data) => request.post('/club/coaches', data)
export const updateClubCoach = (id, data) => request.put(`/club/coaches/${id}`, data)
export const updateClubCoachStatus = (id, coachStatus) => request.put(`/club/coaches/${id}/status`, { coachStatus })
export const getClubStats = () => request.get('/club/player-season-stats')
export const createClubStat = (data) => request.post('/club/player-season-stats', data)
export const updateClubStat = (id, data) => request.put(`/club/player-season-stats/${id}`, data)
export const getAvailableEnrollmentSeasons = () => request.get('/club/enrollments/available-seasons')
export const createClubEnrollment = (data) => request.post('/club/enrollments', data)
export const getClubEnrollments = () => request.get('/club/enrollments')
export const getClubEnrollment = (id) => request.get(`/club/enrollments/${id}`)
export const getClubSchedules = () => request.get('/club/schedules')
export const getAdminEnrollments = (params) => request.get('/admin/enrollments', { params })
export const getAdminEnrollment = (id) => request.get(`/admin/enrollments/${id}`)

export const getAdminClubs = (params) => request.get('/admin/clubs', { params })
export const getAdminClub = (id) => request.get(`/admin/clubs/${id}`)
export const createAdminClub = (data) => request.post('/admin/clubs', data)
export const updateAdminClub = (id, data) => request.put(`/admin/clubs/${id}`, data)
export const updateAdminClubStatus = (id, clubStatus) => request.put(`/admin/clubs/${id}/status`, { clubStatus })
export const getAdminPlayers = (clubId) => request.get(`/admin/clubs/${clubId}/players`)
export const createAdminPlayer = (clubId, data) => request.post(`/admin/clubs/${clubId}/players`, data)
export const updateAdminPlayer = (id, data) => request.put(`/admin/players/${id}`, data)
export const updateAdminPlayerStatus = (id, playerStatus) => request.put(`/admin/players/${id}/status`, { playerStatus })
export const getAdminCoaches = (clubId) => request.get(`/admin/clubs/${clubId}/coaches`)
export const createAdminCoach = (clubId, data) => request.post(`/admin/clubs/${clubId}/coaches`, data)
export const updateAdminCoach = (id, data) => request.put(`/admin/coaches/${id}`, data)
export const updateAdminCoachStatus = (id, coachStatus) => request.put(`/admin/coaches/${id}/status`, { coachStatus })
