<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { createAdminCoach,createAdminPlayer,getAdminClub,getAdminCoaches,getAdminPlayers,updateAdminCoach,updateAdminCoachStatus,updateAdminPlayer,updateAdminPlayerStatus } from '../../api/club'
const route=useRoute(),router=useRouter(),clubId=Number(route.params.id),club=ref({}),players=ref([]),coaches=ref([]),loading=ref(false)
const playerVisible=ref(false),coachVisible=ref(false),playerId=ref(null),coachId=ref(null),playerRef=ref(),coachRef=ref()
const newPlayer=()=>({playerName:'',shirtNo:1,position:'FORWARD',nationality:'',birthDate:null}),player=reactive(newPlayer())
const newCoach=()=>({coachName:'',title:'',nationality:'',description:''}),coach=reactive(newCoach())
const playerRules={playerName:[{required:true,message:'请输入姓名'}],shirtNo:[{required:true,type:'number',min:1,max:99,message:'球衣号为1～99'}],position:[{required:true,message:'请选择位置'}]}
const coachRules={coachName:[{required:true,message:'请输入姓名'}],title:[{required:true,message:'请输入职务'}]}
const positions=[['GOALKEEPER','守门员'],['DEFENDER','后卫'],['MIDFIELDER','中场'],['FORWARD','前锋']]
const load=async()=>{loading.value=true;try{const [c,p,h]=await Promise.all([getAdminClub(clubId),getAdminPlayers(clubId),getAdminCoaches(clubId)]);club.value=c.data;players.value=p.data;coaches.value=h.data}finally{loading.value=false}}
const openPlayer=(row)=>{playerId.value=row?.playerId||null;Object.assign(player,newPlayer(),row||{});playerVisible.value=true}
const savePlayer=async()=>{await playerRef.value.validate();playerId.value?await updateAdminPlayer(playerId.value,player):await createAdminPlayer(clubId,player);playerVisible.value=false;ElMessage.success('球员已保存');await load()}
const togglePlayer=async(row)=>{await updateAdminPlayerStatus(row.playerId,row.playerStatus==='ACTIVE'?'INACTIVE':'ACTIVE');await load()}
const openCoach=(row)=>{coachId.value=row?.coachId||null;Object.assign(coach,newCoach(),row||{});coachVisible.value=true}
const saveCoach=async()=>{await coachRef.value.validate();coachId.value?await updateAdminCoach(coachId.value,coach):await createAdminCoach(clubId,coach);coachVisible.value=false;ElMessage.success('教练已保存');await load()}
const toggleCoach=async(row)=>{await updateAdminCoachStatus(row.coachId,row.coachStatus==='ACTIVE'?'INACTIVE':'ACTIVE');await load()}
onMounted(load)
</script>
<template><div v-loading="loading"><el-page-header @back="router.push('/admin/clubs')"><template #content><span>{{club.clubName||'俱乐部详情'}}</span></template></el-page-header><el-descriptions :column="3" border class="summary"><el-descriptions-item label="简称">{{club.shortName}}</el-descriptions-item><el-descriptions-item label="城市">{{club.homeCity}}</el-descriptions-item><el-descriptions-item label="状态">{{club.clubStatus}}</el-descriptions-item><el-descriptions-item label="简介" :span="3">{{club.description}}</el-descriptions-item></el-descriptions><el-tabs><el-tab-pane label="球员管理"><div class="actions"><el-button type="primary" @click="openPlayer()">新增球员</el-button></div><el-table :data="players"><el-table-column prop="shirtNo" label="号码" width="80"/><el-table-column prop="playerName" label="姓名"/><el-table-column prop="position" label="位置"/><el-table-column prop="playerStatus" label="状态"/><el-table-column label="操作" width="180"><template #default="{row}"><el-button link type="primary" @click="openPlayer(row)">编辑</el-button><el-button link @click="togglePlayer(row)">{{row.playerStatus==='ACTIVE'?'停用':'启用'}}</el-button></template></el-table-column></el-table></el-tab-pane><el-tab-pane label="教练管理"><div class="actions"><el-button type="primary" @click="openCoach()">新增教练</el-button></div><el-table :data="coaches"><el-table-column prop="coachName" label="姓名"/><el-table-column prop="title" label="职务"/><el-table-column prop="coachStatus" label="状态"/><el-table-column label="操作" width="180"><template #default="{row}"><el-button link type="primary" @click="openCoach(row)">编辑</el-button><el-button link @click="toggleCoach(row)">{{row.coachStatus==='ACTIVE'?'停用':'启用'}}</el-button></template></el-table-column></el-table></el-tab-pane></el-tabs></div>
<el-dialog v-model="playerVisible" :title="playerId?'编辑球员':'新增球员'" width="500px"><el-form ref="playerRef" :model="player" :rules="playerRules" label-width="80px"><el-form-item label="姓名" prop="playerName"><el-input v-model="player.playerName"/></el-form-item><el-form-item label="球衣号" prop="shirtNo"><el-input-number v-model="player.shirtNo" :min="1" :max="99"/></el-form-item><el-form-item label="位置" prop="position"><el-select v-model="player.position"><el-option v-for="p in positions" :key="p[0]" :label="p[1]" :value="p[0]"/></el-select></el-form-item><el-form-item label="国籍"><el-input v-model="player.nationality"/></el-form-item><el-form-item label="出生日期"><el-date-picker v-model="player.birthDate" value-format="YYYY-MM-DD"/></el-form-item></el-form><template #footer><el-button @click="playerVisible=false">取消</el-button><el-button type="primary" @click="savePlayer">保存</el-button></template></el-dialog>
<el-dialog v-model="coachVisible" :title="coachId?'编辑教练':'新增教练'" width="500px"><el-form ref="coachRef" :model="coach" :rules="coachRules" label-width="80px"><el-form-item label="姓名" prop="coachName"><el-input v-model="coach.coachName"/></el-form-item><el-form-item label="职务" prop="title"><el-input v-model="coach.title"/></el-form-item><el-form-item label="国籍"><el-input v-model="coach.nationality"/></el-form-item><el-form-item label="说明"><el-input v-model="coach.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="coachVisible=false">取消</el-button><el-button type="primary" @click="saveCoach">保存</el-button></template></el-dialog></template>
<style scoped>.summary{margin:20px 0}.actions{display:flex;justify-content:flex-end;margin-bottom:12px}</style>
