<script setup>
import {onMounted,ref} from 'vue'
import {getAdminCheckin,getAdminCheckins} from '../../api/checkin'
const records=ref([]),total=ref(0),page=ref(1),result=ref(''),matchId=ref(''),checkerId=ref(''),loading=ref(false),detail=ref(null)
const results=['SUCCESS','CODE_NOT_FOUND','WRONG_MATCH','ORDER_INVALID','TICKET_USED','TICKET_REFUNDED','TICKET_VOID']
const load=async()=>{loading.value=true;try{const d=(await getAdminCheckins({matchId:matchId.value||undefined,checkerId:checkerId.value||undefined,checkResult:result.value||undefined,page:page.value,size:10})).data;records.value=d.records;total.value=d.total}finally{loading.value=false}}
const search=()=>{page.value=1;load()};const show=async id=>{detail.value=(await getAdminCheckin(id)).data};onMounted(load)
</script>
<template><el-card><template #header><div class="head"><b>检票记录</b><div><el-input v-model="matchId" placeholder="比赛ID" style="width:105px"/><el-input v-model="checkerId" placeholder="检票员ID" style="width:115px;margin-left:8px"/><el-select v-model="result" clearable placeholder="全部结果" style="width:180px;margin-left:8px"><el-option v-for="x in results" :key="x" :label="x" :value="x"/></el-select><el-button type="primary" @click="search">查询</el-button></div></div></template><el-table :data="records" v-loading="loading"><el-table-column prop="checkedAt" label="检票时间" min-width="175"/><el-table-column prop="matchName" label="比赛" min-width="210"/><el-table-column prop="checkerUsername" label="检票员"/><el-table-column prop="inputTicketCode" label="输入票码" min-width="210"/><el-table-column label="结果"><template #default="{row}"><el-tag :type="row.checkResult==='SUCCESS'?'success':'danger'">{{row.checkResult}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button link type="primary" @click="show(row.checkinId)">详情</el-button></template></el-table-column></el-table><el-pagination v-if="total>10" v-model:current-page="page" :total="total" :page-size="10" layout="prev,pager,next" @current-change="load"/></el-card><el-dialog v-model="detail" title="检票记录详情" width="600px"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item label="结果">{{detail.checkResult}}</el-descriptions-item><el-descriptions-item label="比赛">{{detail.matchName}}</el-descriptions-item><el-descriptions-item label="检票员">{{detail.checkerName}}（{{detail.checkerUsername}}）</el-descriptions-item><el-descriptions-item label="票码">{{detail.inputTicketCode}}</el-descriptions-item><el-descriptions-item label="座位">{{detail.zoneName}} {{detail.rowLabel}} {{detail.seatLabel}}</el-descriptions-item><el-descriptions-item label="时间">{{detail.checkedAt}}</el-descriptions-item><el-descriptions-item label="说明">{{detail.remark}}</el-descriptions-item></el-descriptions></el-dialog></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:center}.el-pagination{margin-top:16px;justify-content:flex-end}</style>
