import request from '../utils/request'
export const getStadium=(id)=>request.get(`/stadiums/${id}`)
export const getAdminStadiums=(params)=>request.get('/admin/stadiums',{params})
export const getAdminStadium=(id)=>request.get(`/admin/stadiums/${id}`)
export const createStadium=(data)=>request.post('/admin/stadiums',data)
export const updateStadium=(id,data)=>request.put(`/admin/stadiums/${id}`,data)
export const updateStadiumStatus=(id,stadiumStatus)=>request.put(`/admin/stadiums/${id}/status`,{stadiumStatus})
export const getCapacitySummary=(id)=>request.get(`/admin/stadiums/${id}/capacity-summary`)
export const getZones=(stadiumId)=>request.get(`/stadiums/${stadiumId}/zones`)
export const createZone=(stadiumId,data)=>request.post(`/admin/stadiums/${stadiumId}/zones`,data)
export const updateZone=(id,data)=>request.put(`/admin/stadium-zones/${id}`,data)
export const updateZoneStatus=(id,zoneStatus)=>request.put(`/admin/stadium-zones/${id}/status`,{zoneStatus})
export const getLayout=(zoneId)=>request.get(`/stadium-zones/${zoneId}/layout`)
export const createSeat=(zoneId,data)=>request.post(`/admin/stadium-zones/${zoneId}/seats`,data)
export const batchCreateSeats=(zoneId,data)=>request.post(`/admin/stadium-zones/${zoneId}/seats/batch`,data)
export const updateSeat=(id,data)=>request.put(`/admin/stadium-seats/${id}`,data)
export const updateSeatStatus=(id,seatStatus)=>request.put(`/admin/stadium-seats/${id}/status`,{seatStatus})
