<script setup>
import {computed,onMounted,ref} from 'vue'
import {ElMessage} from 'element-plus'
import {createClubEnrollment,getAvailableEnrollmentSeasons,getClubEnrollment,getClubEnrollments,getClubPersonnelOverview,getClubProfile} from '../../api/club'
import {formatDateTime} from '../../utils/format'

const available=ref([]),history=ref([]),profile=ref({}),personnel=ref({players:[],coaches:[]}),loading=ref(false),dialog=ref(false),detailVisible=ref(false),detail=ref({}),season=ref(null)
const starters=computed(()=>personnel.value.players?.filter(p=>p.status==='在队'&&p.lineupRole==='STARTER')||[])
const substitutes=computed(()=>personnel.value.players?.filter(p=>p.status==='在队'&&p.lineupRole==='SUBSTITUTE')||[])
const coaches=computed(()=>personnel.value.coaches?.filter(c=>c.status==='现役')||[])
const positionLabel={GOALKEEPER:'门将',DEFENDER:'后卫',MIDFIELDER:'中场',FORWARD:'前锋'},titleLabel={HEAD_COACH:'主教练',ASSISTANT_COACH:'副教练'},roleLabel={STARTER:'首发',SUBSTITUTE:'替补'}
const load=async()=>{loading.value=true;try{const [a,h,p,o]=await Promise.all([getAvailableEnrollmentSeasons(),getClubEnrollments(),getClubProfile(),getClubPersonnelOverview()]);available.value=a.data;history.value=h.data;profile.value=p.data;personnel.value=o.data}finally{loading.value=false}}
const open=row=>{if(row.timeConflict)return;if(!personnel.value.compliant)return ElMessage.error(personnel.value.message+(personnel.value.reason?`：${personnel.value.reason}`:''));season.value=row;dialog.value=true}
const submit=async()=>{if(!personnel.value.compliant)return ElMessage.error(personnel.value.message);await createClubEnrollment({seasonId:season.value.seasonId});dialog.value=false;ElMessage.success('赛季报名已提交，当前阵容已保存为报名快照');await load()}
const show=async id=>{detail.value=(await getClubEnrollment(id)).data;detailVisible.value=true}
onMounted(load)
</script>

<template>
  <div v-loading="loading">
    <el-card><template #header><h2>可报名赛季</h2></template>
      <el-alert :title="personnel.compliant?'报名将使用当前首发、替补、现役教练和标准私有主场。':'请先完善主场场馆及票务信息后再报名'" :description="personnel.compliant?'':personnel.reason" :type="personnel.compliant?'info':'warning'" :closable="false"/>
      <el-table :data="available" empty-text="当前没有可报名赛季"><el-table-column prop="seasonName" label="赛季"/><el-table-column prop="startDate" label="比赛开始"/><el-table-column prop="endDate" label="比赛结束"/><el-table-column label="报名截止"><template #default="{row}">{{formatDateTime(row.registrationDeadline)}}</template></el-table-column><el-table-column label="剩余名额"><template #default="{row}">{{row.remainingSlots}} / {{row.maxClubs}}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-tag v-if="row.timeConflict" type="warning">时间冲突</el-tag><el-button v-else type="primary" link :disabled="!personnel.compliant" @click="open(row)">确认报名</el-button></template></el-table-column></el-table>
    </el-card>
    <el-card class="section"><template #header><h2>报名记录</h2></template><el-table :data="history" empty-text="暂无报名记录"><el-table-column prop="seasonName" label="赛季"/><el-table-column prop="stadiumName" label="主场"/><el-table-column label="报名时间"><template #default="{row}">{{formatDateTime(row.submittedAt)}}</template></el-table-column><el-table-column prop="playerCount" label="球员"/><el-table-column prop="coachCount" label="教练"/><el-table-column prop="enrollmentStatus" label="状态"/><el-table-column label="操作" width="150"><template #default="{row}"><el-button link @click="show(row.enrollmentId)">查看报名阵容</el-button></template></el-table-column></el-table></el-card>
  </div>
  <el-dialog v-model="dialog" title="确认赛季报名" width="900px"><el-descriptions :column="2" border><el-descriptions-item label="赛季">{{season?.seasonName}}</el-descriptions-item><el-descriptions-item label="标准主场">{{profile.city}} {{profile.stadiumName}}</el-descriptions-item><el-descriptions-item label="主场地址">{{profile.address}}</el-descriptions-item><el-descriptions-item label="容量">{{profile.capacity||0}}座</el-descriptions-item></el-descriptions><h3>首发球员（11名）</h3><el-table :data="starters" max-height="260"><el-table-column prop="shirtNo" label="号码"/><el-table-column prop="playerName" label="姓名"/><el-table-column prop="age" label="年龄"/><el-table-column label="位置"><template #default="{row}">{{positionLabel[row.position]}}</template></el-table-column></el-table><h3>替补球员（{{substitutes.length}}名）</h3><el-table :data="substitutes" max-height="220"><el-table-column prop="shirtNo" label="号码"/><el-table-column prop="playerName" label="姓名"/><el-table-column label="位置"><template #default="{row}">{{positionLabel[row.position]}}</template></el-table-column></el-table><h3>现役教练</h3><el-table :data="coaches"><el-table-column prop="coachName" label="姓名"/><el-table-column label="职务"><template #default="{row}">{{titleLabel[row.title]}}</template></el-table-column></el-table><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="submit">确认提交</el-button></template></el-dialog>
  <el-dialog v-model="detailVisible" title="报名阵容快照" width="850px"><el-descriptions :column="2" border><el-descriptions-item label="赛季">{{detail.seasonName}}</el-descriptions-item><el-descriptions-item label="主场">{{detail.stadiumName}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.enrollmentStatus}}</el-descriptions-item><el-descriptions-item label="提交时间">{{formatDateTime(detail.submittedAt)}}</el-descriptions-item></el-descriptions><h3>报名球员</h3><el-table :data="detail.players"><el-table-column prop="playerName" label="姓名"/><el-table-column prop="shirtNo" label="号码"/><el-table-column label="位置"><template #default="{row}">{{positionLabel[row.position]}}</template></el-table-column><el-table-column label="阵容"><template #default="{row}">{{roleLabel[row.lineupRole]}}</template></el-table-column><el-table-column prop="age" label="年龄"/><el-table-column prop="nationality" label="国籍"/></el-table><h3>报名教练</h3><el-table :data="detail.coaches"><el-table-column prop="coachName" label="姓名"/><el-table-column label="职务"><template #default="{row}">{{titleLabel[row.title]}}</template></el-table-column><el-table-column prop="birthYear" label="出生年份"/><el-table-column prop="nationality" label="国籍"/></el-table></el-dialog>
</template>
<style scoped>.section{margin-top:18px}h2{margin:0}h3{margin:18px 0 10px}</style>
