<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage} from 'element-plus'
import {createClubEnrollment,getAvailableEnrollmentSeasons,getClubCoaches,getClubEnrollment,getClubEnrollments,getClubPlayers,getClubProfile} from '../../api/club'
import {formatDateTime} from '../../utils/format'

const available=ref([]),history=ref([]),profile=ref({}),players=ref([]),coaches=ref([]),loading=ref(false)
const dialog=ref(false),detailVisible=ref(false),detail=ref({}),season=ref(null),selectedPlayers=ref([]),selectedCoaches=ref([]),roles=reactive({})
const activePlayers=computed(()=>players.value.filter(x=>x.playerStatus==='ACTIVE'))
const activeCoaches=computed(()=>coaches.value.filter(x=>x.coachStatus==='ACTIVE'))
const load=async()=>{loading.value=true;try{const [a,h,p,ps,cs]=await Promise.all([getAvailableEnrollmentSeasons(),getClubEnrollments(),getClubProfile(),getClubPlayers(),getClubCoaches()]);available.value=a.data;history.value=h.data;profile.value=p.data;players.value=ps.data;coaches.value=cs.data}finally{loading.value=false}}
const open=row=>{season.value=row;selectedPlayers.value=[];selectedCoaches.value=[];Object.keys(roles).forEach(k=>delete roles[k]);dialog.value=true}
const playerSelection=rows=>{selectedPlayers.value=rows;rows.forEach((p,index)=>{if(!roles[p.playerId])roles[p.playerId]=index<11?'STARTER':'SUBSTITUTE'})}
const submit=async()=>{if(selectedPlayers.value.length<11)return ElMessage.error('至少选择11名球员');if(selectedCoaches.value.length<1)return ElMessage.error('至少选择1名教练');await createClubEnrollment({seasonId:season.value.seasonId,stadiumId:profile.value.homeStadiumId,players:selectedPlayers.value.map(p=>({playerId:p.playerId,lineupRole:roles[p.playerId]})),coachIds:selectedCoaches.value.map(c=>c.coachId)});dialog.value=false;ElMessage.success('赛季报名已提交');await load()}
const show=async id=>{detail.value=(await getClubEnrollment(id)).data;detailVisible.value=true}
onMounted(load)
</script>

<template><div v-loading="loading"><el-card><template #header><h2>可报名赛季</h2></template><el-alert title="报名使用当前俱乐部默认主场；系统不会接受其他场馆ID。" type="info" :closable="false"/><el-table :data="available" empty-text="当前没有可报名赛季"><el-table-column prop="seasonName" label="赛季"/><el-table-column prop="startDate" label="比赛开始"/><el-table-column prop="endDate" label="比赛结束"/><el-table-column label="报名截止"><template #default="{row}">{{formatDateTime(row.registrationDeadline)}}</template></el-table-column><el-table-column label="剩余名额"><template #default="{row}">{{row.remainingSlots}} / {{row.maxClubs}}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button type="primary" link @click="open(row)">准备并报名</el-button></template></el-table-column></el-table></el-card>
<el-card class="section"><template #header><h2>报名记录</h2></template><el-table :data="history"><el-table-column prop="seasonName" label="赛季"/><el-table-column prop="stadiumName" label="主场"/><el-table-column prop="submittedAt" label="报名时间"/><el-table-column prop="playerCount" label="球员"/><el-table-column prop="coachCount" label="教练"/><el-table-column prop="enrollmentStatus" label="状态"/><el-table-column label="最近比赛"><template #default="{row}"><span v-if="row.nextMatchTime">{{formatDateTime(row.nextMatchTime)}}（{{row.daysUntilNextMatch}}天）</span><span v-else>暂无已安排比赛</span></template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button link @click="show(row.enrollmentId)">详情</el-button></template></el-table-column></el-table></el-card></div>
<el-dialog v-model="dialog" title="提交赛季报名" width="900px"><el-descriptions :column="2" border><el-descriptions-item label="赛季">{{season?.seasonName}}</el-descriptions-item><el-descriptions-item label="默认主场">{{profile.homeAddress||'—'}}（ID {{profile.homeStadiumId||'未配置'}}）</el-descriptions-item></el-descriptions><h3>选择球员（至少11名）</h3><el-table :data="activePlayers" height="320" @selection-change="playerSelection"><el-table-column type="selection" width="48"/><el-table-column prop="playerName" label="姓名"/><el-table-column prop="shirtNo" label="号码"/><el-table-column prop="position" label="位置"/><el-table-column label="阵容角色" width="170"><template #default="{row}"><el-select v-model="roles[row.playerId]"><el-option label="首发" value="STARTER"/><el-option label="替补" value="SUBSTITUTE"/></el-select></template></el-table-column></el-table><h3>选择教练（至少1名）</h3><el-select v-model="selectedCoaches" multiple value-key="coachId" style="width:100%"><el-option v-for="c in activeCoaches" :key="c.coachId" :label="`${c.coachName} · ${c.title}`" :value="c"/></el-select><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="submit">确认提交</el-button></template></el-dialog>
<el-dialog v-model="detailVisible" title="报名详情" width="800px"><el-descriptions :column="2" border><el-descriptions-item label="赛季">{{detail.seasonName}}</el-descriptions-item><el-descriptions-item label="主场">{{detail.stadiumName}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.enrollmentStatus}}</el-descriptions-item><el-descriptions-item label="提交时间">{{formatDateTime(detail.submittedAt)}}</el-descriptions-item></el-descriptions><h3>报名球员</h3><el-table :data="detail.players"><el-table-column prop="playerName" label="姓名"/><el-table-column prop="shirtNo" label="号码"/><el-table-column prop="position" label="位置"/><el-table-column prop="lineupRole" label="首发/替补"/><el-table-column prop="age" label="年龄"/></el-table><h3>报名教练</h3><el-table :data="detail.coaches"><el-table-column prop="coachName" label="姓名"/><el-table-column prop="title" label="职务"/></el-table></el-dialog></template>
<style scoped>.section{margin-top:18px}h2{margin:0}h3{margin:18px 0 10px}</style>
