<script setup>
import {onMounted,ref} from 'vue'
import {getClubData} from '../../api/statistics'
const data=ref({revenue:0,performance:{},rankings:[]}),loading=ref(false),money=value=>`￥${Number(value||0).toFixed(2)}`
const load=async()=>{loading.value=true;try{data.value=(await getClubData()).data}finally{loading.value=false}}
onMounted(load)
</script>
<template><div v-loading="loading"><h2>俱乐部数据</h2><el-card class="revenue"><span>已结束有效比赛累计收益</span><strong>{{money(data.revenue)}}</strong></el-card><el-card class="section"><template #header><b>比赛成绩</b></template><el-row :gutter="12"><el-col v-for="item in [['参赛场数','matchesPlayed'],['总积分','points'],['胜','wins'],['平','draws'],['负','losses'],['进球','goalsFor'],['失球','goalsAgainst'],['净胜球','goalDifference']]" :key="item[1]" :span="3"><div class="metric"><span>{{item[0]}}</span><b>{{data.performance?.[item[1]]||0}}</b></div></el-col></el-row></el-card><el-card class="section"><template #header><b>排行榜</b></template><el-table :data="data.rankings" empty-text="暂无俱乐部数据"><el-table-column type="index" label="排名" width="70"/><el-table-column label="俱乐部" min-width="180"><template #default="{row}"><div class="club"><el-avatar :size="34" :src="row.logoUrl||undefined">{{row.clubName?.slice(0,1)}}</el-avatar><span>{{row.clubName}}</span></div></template></el-table-column><el-table-column prop="matchesPlayed" label="场次"/><el-table-column prop="points" label="积分"/><el-table-column prop="wins" label="胜"/><el-table-column prop="draws" label="平"/><el-table-column prop="losses" label="负"/><el-table-column prop="goalsFor" label="进球"/><el-table-column prop="goalsAgainst" label="失球"/><el-table-column prop="goalDifference" label="净胜球"/></el-table></el-card></div></template>
<style scoped>h2{margin-top:0}.revenue :deep(.el-card__body){display:flex;justify-content:space-between;align-items:center}.revenue span,.metric span{color:#64748b}.revenue strong{font-size:30px;color:#b45309}.section{margin-top:16px}.metric{background:#f8fafc;padding:16px;text-align:center;border-radius:8px}.metric span{display:block;margin-bottom:8px}.metric b{font-size:22px}.club{display:flex;align-items:center;gap:10px}</style>
