<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {cleanupClubCoach,createClubCoach,getClubCoaches,updateClubCoach,updateClubCoachStatus} from '../../api/club'

const rows=ref([]),loading=ref(false),visible=ref(false),editingId=ref(null),organized=ref(false),formRef=ref()
const empty=()=>({coachName:'',nationality:'',birthYear:null,title:'ASSISTANT_COACH',description:''}),form=reactive(empty())
const titleLabel={HEAD_COACH:'主教练',ASSISTANT_COACH:'副教练'}
const rules={coachName:[{required:true,message:'请输入教练姓名'}],nationality:[{required:true,message:'请输入国籍'}],birthYear:[{required:true,message:'请输入出生年份'}],title:[{required:true,message:'请选择职务'}]}
const displayed=computed(()=>!organized.value?rows.value:[...rows.value].sort((a,b)=>(a.coachStatus==='ACTIVE'?0:1)-(b.coachStatus==='ACTIVE'?0:1)||(a.title==='HEAD_COACH'?0:1)-(b.title==='HEAD_COACH'?0:1)||a.coachId-b.coachId))
const load=async()=>{loading.value=true;try{rows.value=(await getClubCoaches()).data}finally{loading.value=false}}
const open=row=>{editingId.value=row?.coachId||null;Object.assign(form,empty(),row||{});visible.value=true}
const save=async()=>{await formRef.value.validate();editingId.value?await updateClubCoach(editingId.value,{title:form.title}):await createClubCoach({...form,birthYear:Number(form.birthYear)});visible.value=false;ElMessage.success('保存成功');await load()}
const leave=async row=>{await ElMessageBox.confirm(`确认将「${row.coachName}」设为离队？`,'离队确认',{type:'warning'});await updateClubCoachStatus(row.coachId,'INACTIVE');ElMessage.success('已离队');await load()}
const restore=async row=>{await updateClubCoachStatus(row.coachId,'ACTIVE');ElMessage.success('已归队');await load()}
const cleanup=async row=>{await ElMessageBox.confirm(`确认清理离队教练「${row.coachName}」？`,'清理确认',{type:'warning'});await cleanupClubCoach(row.coachId);ElMessage.success('已清理');await load()}
onMounted(load)
</script>
<template><el-card><template #header><div class="head"><h2>教练管理</h2><div><el-button @click="organized=!organized">{{organized?'恢复添加顺序':'整理'}}</el-button><el-button type="primary" @click="open()">新增教练</el-button></div></div></template><el-table v-loading="loading" :data="displayed" empty-text="暂无教练"><el-table-column prop="coachName" label="姓名"/><el-table-column prop="nationality" label="国籍"/><el-table-column prop="birthYear" label="出生年份"><template #default="{row}">{{row.birthYear??'-'}}</template></el-table-column><el-table-column label="职务"><template #default="{row}">{{titleLabel[row.title]||'-'}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.coachStatus==='ACTIVE'?'success':'info'">{{row.coachStatus==='ACTIVE'?'现役':'离队'}}</el-tag></template></el-table-column><el-table-column label="操作" width="210"><template #default="{row}"><template v-if="row.coachStatus==='ACTIVE'"><el-button link type="primary" @click="open(row)">调整</el-button><el-button link type="danger" @click="leave(row)">离队</el-button></template><template v-else><el-button link type="success" @click="restore(row)">归队</el-button><el-button link type="danger" @click="cleanup(row)">清理</el-button></template></template></el-table-column></el-table></el-card><el-dialog v-model="visible" :title="editingId?'调整教练':'新增教练'" width="520px"><el-form ref="formRef" :model="form" :rules="rules" label-width="90px"><el-form-item label="姓名" prop="coachName"><el-input v-model="form.coachName" :disabled="!!editingId"/></el-form-item><el-form-item label="国籍" prop="nationality"><el-input v-model="form.nationality" :disabled="!!editingId"/></el-form-item><el-form-item label="出生年份" prop="birthYear"><el-input v-model="form.birthYear" inputmode="numeric" :disabled="!!editingId"/></el-form-item><el-form-item label="职务" prop="title"><el-select v-model="form.title"><el-option label="主教练" value="HEAD_COACH"/><el-option label="副教练" value="ASSISTANT_COACH"/></el-select></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></template>
<style scoped>.head{display:flex;align-items:center;justify-content:space-between}.head h2{margin:0}</style>
