<script setup>
import {computed,onBeforeUnmount,onMounted,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {cancelOrder,getOrder,payOrder} from '../../api/order'
import {applyRefund} from '../../api/refund'
import {formatMoney} from '../../utils/format'
import {useSystemTimeStore} from '../../stores/systemTime'
const route=useRoute(),router=useRouter(),systemTime=useSystemTimeStore(),data=ref(null),loading=ref(false),paying=ref(false),cancelling=ref(false),refunding=ref(false),refreshing=ref(false);let timer
const order=computed(()=>data.value?.order||{}),remaining=computed(()=>Math.max(0,new Date(order.value.expireTime||0).getTime()-systemTime.nowMs))
const countdown=computed(()=>{const s=Math.floor(remaining.value/1000);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`})
const load=async()=>{loading.value=true;try{data.value=(await getOrder(route.params.id)).data}finally{loading.value=false}}
const cancel=async()=>{await ElMessageBox.confirm('确认取消该待支付订单并释放座位？','取消订单',{type:'warning'});cancelling.value=true;try{data.value=(await cancelOrder(route.params.id)).data;ElMessage.success('订单已取消，座位已经释放')}finally{cancelling.value=false}}
const pay=async result=>{paying.value=true;try{const r=(await payOrder(route.params.id,result)).data;data.value=r.orderDetail;if(result==='SUCCESS')ElMessage.success(r.idempotent?'订单已经支付，请勿重复操作':'模拟支付成功，电子票已生成');else ElMessage.warning('模拟支付失败，可在订单有效期内重试')}finally{paying.value=false}}
const refund=async()=>{const {value}=await ElMessageBox.prompt(`本系统仅支持整单全额退票，预计退款${formatMoney(order.value.totalAmount)}；须在比赛开始24小时前申请。请输入原因：`,'申请退票',{inputType:'textarea',inputValidator:v=>v?.trim()?'': '请输入退票原因'});refunding.value=true;try{const r=(await applyRefund(route.params.id,value)).data;ElMessage.success('退票申请已提交');router.push(`/user/refunds/${r.refundId}`)}finally{refunding.value=false}}
onMounted(async()=>{await Promise.all([load(),systemTime.sync()]);timer=setInterval(async()=>{systemTime.tick();if(order.value.orderStatus==='PENDING_PAYMENT'&&remaining.value===0&&!refreshing.value){refreshing.value=true;try{await load()}finally{refreshing.value=false}}},1000)})
onBeforeUnmount(()=>clearInterval(timer))
</script>
<template><el-card v-loading="loading"><template #header><el-page-header @back="router.push('/user/orders')"><template #content>订单详情</template></el-page-header></template><template v-if="data"><el-alert v-if="order.orderStatus==='PENDING_PAYMENT'" type="warning" :closable="false" :title="remaining?`支付剩余时间 ${countdown}`:'订单正在关闭，请稍候刷新'"/><el-alert v-if="order.orderStatus==='REFUND_PENDING'" title="退票申请审核中，座位和电子票暂时保留" type="warning" :closable="false"/><el-descriptions :column="2" border class="details"><el-descriptions-item label="订单号">{{order.orderNo}}</el-descriptions-item><el-descriptions-item label="状态"><StatusTag :value="order.orderStatus"/></el-descriptions-item><el-descriptions-item label="比赛">{{order.homeClubName}} vs {{order.awayClubName}}</el-descriptions-item><el-descriptions-item label="比赛时间">{{$formatDateTime(order.matchTime)}}</el-descriptions-item><el-descriptions-item label="场馆">{{order.stadiumName}}</el-descriptions-item><el-descriptions-item label="比赛票区">{{order.zoneName}}</el-descriptions-item><el-descriptions-item label="数量">{{order.ticketCount}}张</el-descriptions-item><el-descriptions-item label="总金额">{{$formatMoney(order.totalAmount)}}</el-descriptions-item><el-descriptions-item v-if="order.paidAt" label="支付时间">{{$formatDateTime(order.paidAt)}}</el-descriptions-item><el-descriptions-item v-if="order.cancelReason" label="取消原因">{{$statusLabel(order.cancelReason)}}</el-descriptions-item></el-descriptions><h3>已分配座位</h3><el-table :data="data.items" empty-text="暂无座位明细"><el-table-column prop="rowLabel" label="排"/><el-table-column prop="seatLabel" label="座位"/><el-table-column label="单价"><template #default="{row}">{{$formatMoney(row.unitPrice)}}</template></el-table-column><el-table-column label="明细状态"><template #default="{row}"><StatusTag :value="row.itemStatus"/></template></el-table-column></el-table><el-descriptions v-if="data.payment" :column="2" border class="details"><el-descriptions-item label="支付流水">{{data.payment.paymentNo}}</el-descriptions-item><el-descriptions-item label="支付状态"><StatusTag :value="data.payment.payStatus"/></el-descriptions-item></el-descriptions><div v-if="data.tickets?.length"><h3>电子票</h3><el-button v-for="t in data.tickets" :key="t.ticketId" type="success" plain @click="router.push(`/user/tickets/${t.ticketId}`)">{{t.rowNo}}排 {{t.seatNo}}座</el-button></div><div v-if="order.orderStatus==='PENDING_PAYMENT'" class="pay-actions"><el-button type="primary" :loading="paying" :disabled="!remaining||cancelling" @click="pay('SUCCESS')">模拟支付成功</el-button><el-button :loading="paying" :disabled="!remaining||cancelling" @click="pay('FAILED')">模拟支付失败</el-button><el-button type="danger" plain :loading="cancelling" :disabled="paying" @click="cancel">取消订单</el-button></div><el-button v-if="order.orderStatus==='PAID'" class="pay-actions" type="warning" :loading="refunding" @click="refund">申请整单退票</el-button></template><el-empty v-else-if="!loading" description="订单不存在或无权查看"/></el-card></template>
<style scoped>.details{margin:16px 0}.pay-actions{display:flex;gap:10px;margin-top:16px}</style>
