import request from '../utils/request'

export const getClubs = (params={page:1,size:100}) => request.get('/clubs', { params })
export const getUserClubDetail = (clubId) => request.get(`/user/clubs/${clubId}`)

export const getClubProfile = () => request.get('/club/profile')
export const updateClubProfile = (data) => request.put('/club/profile', data)
export const uploadClubLogo = (file) => { const data=new FormData();data.append('file',file);return request.post('/club/profile/logo',data,{headers:{'Content-Type':'multipart/form-data'}}) }
export const getClubPersonnelOverview = () => request.get('/club/personnel/overview')
export const getClubPlayers = () => request.get('/club/players')
export const createClubPlayer = (data) => request.post('/club/players', data)
export const updateClubPlayer = (id, data) => request.put(`/club/players/${id}`, data)
export const updateClubPlayerStatus = (id, playerStatus) => request.put(`/club/players/${id}/status`, { playerStatus })
export const returnClubPlayer = (id,data) => request.put(`/club/players/${id}/return`,data)
export const cleanupClubPlayer = (id) => request.delete(`/club/players/${id}`)
export const getClubCoaches = () => request.get('/club/coaches')
export const createClubCoach = (data) => request.post('/club/coaches', data)
export const updateClubCoach = (id, data) => request.put(`/club/coaches/${id}`, data)
export const updateClubCoachStatus = (id, coachStatus) => request.put(`/club/coaches/${id}/status`, { coachStatus })
export const cleanupClubCoach = (id) => request.delete(`/club/coaches/${id}`)
export const getClubStats = () => request.get('/club/player-season-stats')
export const createClubStat = (data) => request.post('/club/player-season-stats', data)
export const updateClubStat = (id, data) => request.put(`/club/player-season-stats/${id}`, data)
export const getAvailableEnrollmentSeasons = () => request.get('/club/enrollments/available-seasons')
export const createClubEnrollment = (data) => request.post('/club/enrollments', data)
export const getClubEnrollments = () => request.get('/club/enrollments')
export const getClubEnrollment = (id) => request.get(`/club/enrollments/${id}`)
export const getClubSchedules = () => request.get('/club/schedules')
export const getAdminEnrollments = (params) => request.get('/admin/enrollments', { params })
export const getAdminEnrollment = (id) => request.get(`/admin/enrollments/${id}`)

export const getAdminClubs = (params) => request.get('/admin/clubs', { params })
export const getAdminClub = (id) => request.get(`/admin/clubs/${id}`)
export const updateAdminClubStatus = (id, clubStatus) => request.put(`/admin/clubs/${id}/status`, { clubStatus })
export const updateAdminClubLeaderStatus = (id, userStatus) => request.put(`/admin/clubs/${id}/leader-status`, { userStatus })
