import request from '../utils/request'
export const getMatches=(params)=>request.get('/matches',{params})
export const getMatch=(id)=>request.get(`/matches/${id}`)
export const getStadiums=()=>request.get('/stadiums')
export const createMatch=(data)=>request.post('/admin/matches',data)
export const updateMatch=(id,data)=>request.put(`/admin/matches/${id}`,data)
export const updateMatchStatus=(id,matchStatus)=>request.put(`/admin/matches/${id}/status`,{matchStatus})
export const submitMatchResult=(id,data)=>request.post(`/admin/matches/${id}/result-submissions`,data)
export const getMatchResult=id=>request.get(`/admin/matches/${id}/result-submissions`)
export const getPendingResultReviews=()=>request.get('/admin/result-reviews')
export const confirmMatchResult=(id,data)=>request.post(`/admin/result-reviews/${id}/confirm`,data)
export const getResultReminders=(params)=>request.get('/admin/matches/result-reminders',{params})
