package com.example.leagueticket;

import com.example.leagueticket.dto.*;import com.example.leagueticket.service.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.test.context.ActiveProfiles;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.*;import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest @ActiveProfiles("dev") @Transactional
@EnabledIfEnvironmentVariable(named="RUN_DB_TESTS",matches="true")
class Phase24EventAdminIntegrationTest {
 @Autowired org.springframework.jdbc.core.JdbcTemplate jdbc;@Autowired MatchResultWorkflowService results;@Autowired RefundService refunds;@Autowired SystemTimeService time;@Autowired SeasonInfoService seasons;@Autowired DoubleRoundRobinSchedulePlanner planner;
 long seasonId,roundId,clubA,clubB,stadiumId,eventA,eventB,admin;
 @BeforeEach void setup(){clubA=id("SELECT club_id FROM club_info ORDER BY club_id LIMIT 1");clubB=id("SELECT club_id FROM club_info ORDER BY club_id LIMIT 1 OFFSET 1");stadiumId=id("SELECT home_stadium_id FROM club_info WHERE club_id="+clubA);eventA=id("SELECT u.user_id FROM sys_user u JOIN sys_role r ON r.role_id=u.role_id WHERE r.role_code='EVENT_ADMIN' LIMIT 1");admin=id("SELECT u.user_id FROM sys_user u JOIN sys_role r ON r.role_id=u.role_id WHERE r.role_code='ADMIN' LIMIT 1");long eventRole=id("SELECT role_id FROM sys_role WHERE role_code='EVENT_ADMIN'");jdbc.update("INSERT INTO sys_user(username,phone,password_hash,display_name,employee_no,role_id,user_status) VALUES('IT24_EVENT','13924240001','x','IT24 EVENT','EA2424',?,'ENABLED')",eventRole);eventB=id("SELECT user_id FROM sys_user WHERE employee_no='EA2424'");LocalDateTime now=time.now();jdbc.update("INSERT INTO season_info(season_name,start_date,end_date,registration_start_time,registration_deadline,ticket_sale_start_time,max_clubs,season_status) VALUES(?,?,?,?,?,?,2,'DRAFT')","IT24-"+System.nanoTime(),now.toLocalDate().minusDays(1),now.toLocalDate().plusDays(30),now.minusMonths(2),now.minusMonths(1),now.minusDays(20));seasonId=id("SELECT MAX(season_id) FROM season_info");jdbc.update("INSERT INTO round_info(season_id,round_no,round_name,start_date,end_date,round_status) VALUES(?,1,'IT24轮',?,?,'DRAFT')",seasonId,now.toLocalDate().minusDays(1),now.toLocalDate().plusDays(30));roundId=id("SELECT MAX(round_id) FROM round_info");jdbc.update("INSERT INTO club_season_record(season_id,club_id) VALUES(?,?),(?,?)",seasonId,clubA,seasonId,clubB);}
 @Test void oneSubmissionWaitsTwoEqualPublishAndConflictNeedsAdmin(){long one=match(time.now().minusHours(2));var first=results.submit(one,eventA,new MatchScoreRequest(2,1));assertThat(first.reviewReason()).isEqualTo("SINGLE_SUBMISSION");assertThat(score(one)).isNull();var published=results.submit(one,eventB,new MatchScoreRequest(2,1));assertThat(published.reviewStatus()).isEqualTo("AUTO_PUBLISHED");assertThat(score(one)).isEqualTo("2:1:FINISHED");long conflict=match(time.now().minusHours(3));results.submit(conflict,eventA,new MatchScoreRequest(1,0));var pending=results.submit(conflict,eventB,new MatchScoreRequest(0,1));assertThat(pending.reviewReason()).isEqualTo("CONFLICT");assertThat(score(conflict)).isNull();results.confirm(conflict,admin,new MatchScoreRequest(3,2));assertThat(score(conflict)).isEqualTo("3:2:FINISHED");}
 @Test void automaticRefundUsesHundredAndFiftyPercentBoundariesAndRestoresInventory(){long full=paidOrder(time.now().plusDays(7).plusMinutes(1));var a=refunds.apply(id("SELECT user_id FROM sys_user u JOIN sys_role r ON r.role_id=u.role_id WHERE r.role_code='USER' LIMIT 1"),full,new RefundApplyRequest("IT24"));assertThat(a.refundRate()).isEqualByComparingTo("1.00");assertThat(a.feeAmount()).isEqualByComparingTo("0.00");assertThat(state(full)).isEqualTo("REFUNDED:REFUNDED:AVAILABLE");long half=paidOrder(time.now().plusDays(6));var b=refunds.apply(id("SELECT user_id FROM sys_user u JOIN sys_role r ON r.role_id=u.role_id WHERE r.role_code='USER' LIMIT 1"),half,new RefundApplyRequest("IT24"));assertThat(b.refundRate()).isEqualByComparingTo("0.50");assertThat(b.refundAmount()).isEqualByComparingTo("50.00");assertThat(b.feeAmount()).isEqualByComparingTo("50.00");}
 @Test void seasonCreationDerivesEveryWindowAndExpectedEndFromTheSharedPlanner(){LocalDateTime now=time.now();LocalDate start=now.plusMonths(1).plusDays(2).toLocalDate();var season=seasons.create(new SeasonRequest("IT24赛季名称",start,4));assertThat(season.getSeasonName()).isEqualTo("IT24赛季名称");LocalDateTime todayTwenty=now.toLocalDate().atTime(20,0);assertThat(season.getRegistrationStartTime()).isEqualTo(now.isBefore(todayTwenty)?todayTwenty:todayTwenty.plusDays(1));assertThat(season.getRegistrationDeadline()).isEqualTo(start.minusDays(15).atTime(19,59));assertThat(season.getTicketSaleStartTime()).isEqualTo(start.minusDays(14).atTime(20,0));assertThat(season.getEndDate()).isEqualTo(planner.expectedEndDate(4,start));}
 private long match(LocalDateTime at){jdbc.update("INSERT INTO match_info(season_id,round_id,home_club_id,away_club_id,stadium_id,match_time,sale_start_time,sale_end_time,match_status) VALUES(?,?,?,?,?,?,?,?,'PUBLISHED')",seasonId,roundId,clubA,clubB,stadiumId,at,at.minusDays(20),at.minusHours(1));return id("SELECT MAX(match_id) FROM match_info");}
 private long paidOrder(LocalDateTime at){long match=match(at);long zone=id("SELECT stadium_zone_id FROM stadium_zone WHERE stadium_id="+stadiumId+" LIMIT 1"),seat=id("SELECT stadium_seat_id FROM stadium_seat WHERE stadium_zone_id="+zone+" LIMIT 1");jdbc.update("INSERT INTO match_ticket_zone(match_id,stadium_zone_id,created_by,zone_name_snapshot,ticket_price,zone_status,sale_start_time,sale_end_time) VALUES(?,?,?,'IT24',100,'ON_SALE',?,?)",match,zone,eventA,at.minusDays(20),at.minusHours(1));long matchZone=id("SELECT MAX(match_zone_id) FROM match_ticket_zone");jdbc.update("INSERT INTO match_seat_inventory(match_id,match_zone_id,stadium_seat_id,inventory_status) VALUES(?,?,?,'SOLD')",match,matchZone,seat);long inventory=id("SELECT MAX(inventory_id) FROM match_seat_inventory"),user=id("SELECT user_id FROM sys_user u JOIN sys_role r ON r.role_id=u.role_id WHERE r.role_code='USER' LIMIT 1");String no="IT24"+System.nanoTime();jdbc.update("INSERT INTO ticket_order(order_no,user_id,match_id,match_zone_id,ticket_count,total_amount,order_status,expire_time,paid_at) VALUES(?,?,?,?,1,100,'PAID',?,?)",no,user,match,matchZone,time.now().plusMinutes(10),time.now());long order=id("SELECT MAX(order_id) FROM ticket_order");jdbc.update("INSERT INTO order_item(order_id,inventory_id,ticket_price,zone_name_snapshot,row_no_snapshot,seat_no_snapshot,item_status) VALUES(?,?,100,'IT24','1','1','PAID')",order,inventory);long item=id("SELECT MAX(item_id) FROM order_item");jdbc.update("INSERT INTO payment_record(payment_no,order_id,pay_amount,pay_status,pay_time) VALUES(?,?,100,'SUCCESS',?)","P"+no,order,time.now());jdbc.update("INSERT INTO e_ticket(ticket_code,order_id,item_id,ticket_status) VALUES(?,?,?,'UNUSED')","T"+no,order,item);return order;}
 private String score(long match){return jdbc.query("SELECT CONCAT(home_score,':',away_score,':',match_status) FROM match_info WHERE match_id=?",rs->rs.next()?rs.getString(1):null,match);}private String state(long order){return jdbc.queryForObject("SELECT CONCAT(o.order_status,':',oi.item_status,':',i.inventory_status) FROM ticket_order o JOIN order_item oi ON oi.order_id=o.order_id JOIN match_seat_inventory i ON i.inventory_id=oi.inventory_id WHERE o.order_id=?",String.class,order);}private long id(String sql){return jdbc.queryForObject(sql,Long.class);}
}
