package com.example.leagueticket.service.impl;
import com.example.leagueticket.dto.MatchScoreRequest;import com.example.leagueticket.entity.*;import com.example.leagueticket.exception.BusinessException;import com.example.leagueticket.mapper.*;import com.example.leagueticket.service.*;import com.example.leagueticket.vo.MatchResultWorkflowResponse;import lombok.RequiredArgsConstructor;import org.springframework.context.annotation.Profile;import org.springframework.dao.DuplicateKeyException;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Service @Profile("dev") @RequiredArgsConstructor public class MatchResultWorkflowServiceImpl implements MatchResultWorkflowService {
 private final MatchResultMapper mapper;private final MatchInfoMapper matchMapper;private final SystemTimeService timeService;private final StandingRecalculateService standingService;
 @Transactional public MatchResultWorkflowResponse submit(Long matchId,Long eventAdminId,MatchScoreRequest request){MatchInfo match=matchMapper.findByIdForUpdate(matchId);requireSubmittable(match);LocalDateTime now=timeService.now();if(now.isBefore(match.getMatchTime()))throw new BusinessException(HttpStatus.CONFLICT,"比赛尚未开始，暂不能提交比分");MatchResultSubmission submission=new MatchResultSubmission();submission.setMatchId(matchId);submission.setEventAdminId(eventAdminId);submission.setHomeScore(request.homeScore());submission.setAwayScore(request.awayScore());submission.setSubmittedAt(now);try{mapper.insertSubmission(submission);}catch(DuplicateKeyException e){throw new BusinessException(HttpStatus.CONFLICT,"同一赛事管理员不得重复或覆盖提交");}List<MatchResultSubmission> values=mapper.findSubmissions(matchId);long distinct=values.stream().map(v->v.getHomeScore()+":"+v.getAwayScore()).distinct().count();MatchResultReview review=new MatchResultReview();review.setMatchId(matchId);if(values.size()>=2&&distinct==1){review.setReviewStatus("AUTO_PUBLISHED");review.setReviewReason("CONSENSUS");review.setFinalHomeScore(request.homeScore());review.setFinalAwayScore(request.awayScore());review.setConfirmedAt(now);mapper.saveReview(review);publish(match,request.homeScore(),request.awayScore());}else{review.setReviewStatus("PENDING_ADMIN_REVIEW");review.setReviewReason(values.size()==1?"SINGLE_SUBMISSION":"CONFLICT");mapper.saveReview(review);}return detail(matchId);}
 public MatchResultWorkflowResponse detail(Long matchId){MatchResultReview r=mapper.findReview(matchId);List<MatchResultSubmission> submissions=mapper.findSubmissions(matchId);return r==null?new MatchResultWorkflowResponse(matchId,null,null,null,null,null,null,submissions):new MatchResultWorkflowResponse(matchId,r.getReviewStatus(),r.getReviewReason(),r.getFinalHomeScore(),r.getFinalAwayScore(),r.getConfirmedBy(),r.getConfirmedAt(),submissions);}
 public List<MatchResultWorkflowResponse> pending(){return mapper.findPending().stream().map(r->detail(r.getMatchId())).toList();}
 @Transactional public MatchResultWorkflowResponse confirm(Long matchId,Long adminId,MatchScoreRequest request){MatchInfo match=matchMapper.findByIdForUpdate(matchId);MatchResultReview current=mapper.findReviewForUpdate(matchId);if(current==null||!"PENDING_ADMIN_REVIEW".equals(current.getReviewStatus()))throw new BusinessException(HttpStatus.CONFLICT,"赛果不在ADMIN待确认状态");LocalDateTime now=timeService.now();MatchResultReview review=new MatchResultReview();review.setMatchId(matchId);review.setReviewStatus("ADMIN_CONFIRMED");review.setReviewReason("ADMIN_DECISION");review.setFinalHomeScore(request.homeScore());review.setFinalAwayScore(request.awayScore());review.setConfirmedBy(adminId);review.setConfirmedAt(now);mapper.saveReview(review);publish(match,request.homeScore(),request.awayScore());return detail(matchId);}
 private void requireSubmittable(MatchInfo match){if(match==null)throw new BusinessException(HttpStatus.NOT_FOUND,"match not found");if(!Set.of("PUBLISHED","IN_PROGRESS").contains(match.getMatchStatus()))throw new BusinessException(HttpStatus.CONFLICT,"当前比赛状态不可提交赛果");}
 private void publish(MatchInfo match,int home,int away){if(mapper.publish(match.getMatchId(),home,away)!=1)throw new BusinessException(HttpStatus.CONFLICT,"正式赛果发布失败");standingService.recalculate(match.getSeasonId());}
}
