<script setup>
import {onMounted,reactive,ref} from 'vue'
import {useRouter} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {getAdminClubs,updateAdminClubLeaderStatus,updateAdminClubStatus} from '../../api/club'
import {approveClubUser,getClubApplications} from '../../api/user'
import {accountStatusLabel,clubStatusLabel,statusType} from '../../constants/status'
const router=useRouter(),rows=ref([]),pending=ref([]),total=ref(0),loading=ref(false)
const query=reactive({name:'',status:'',page:1,size:10})
const load=async()=>{loading.value=true;try{const [clubs,applications]=await Promise.all([getAdminClubs(query),getClubApplications({page:1,size:100})]);rows.value=clubs.data.records;total.value=clubs.data.total;pending.value=applications.data.records}finally{loading.value=false}}
const toggleClub=async row=>{await updateAdminClubStatus(row.clubId,row.clubStatus==='ACTIVE'?'DISABLED':'ACTIVE');ElMessage.success('俱乐部状态已更新');await load()}
const toggleLeader=async row=>{if(!row.leaderStatus)return;await updateAdminClubLeaderStatus(row.clubId,row.leaderStatus==='ENABLED'?'DISABLED':'ENABLED');ElMessage.success('负责人账号状态已更新');await load()}
const approve=async row=>{await ElMessageBox.confirm(`将创建新俱乐部“${row.clubApplyName}”并绑定负责人，确认通过？`,'CLUB注册审核');await approveClubUser(row.userId);ElMessage.success('审核通过并完成负责人绑定');await load()}
onMounted(load)
</script>
<template><el-card><template #header><h2>俱乐部管理</h2></template><el-form inline><el-form-item label="名称"><el-input v-model="query.name" clearable/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option label="已启用" value="ACTIVE"/><el-option label="已停用" value="DISABLED"/></el-select></el-form-item><el-button type="primary" @click="load">查询</el-button></el-form><el-table v-loading="loading" :data="rows"><el-table-column prop="clubName" label="名称"/><el-table-column label="负责人"><template #default="{row}">{{row.leaderName||'未绑定负责人'}}</template></el-table-column><el-table-column label="负责人手机号"><template #default="{row}">{{row.leaderPhone||'—'}}</template></el-table-column><el-table-column label="负责人状态"><template #default="{row}"><el-tag v-if="row.leaderStatus" :type="statusType(row.leaderStatus)">{{accountStatusLabel(row.leaderStatus)}}</el-tag><span v-else>—</span></template></el-table-column><el-table-column label="俱乐部状态"><template #default="{row}"><el-tag :type="statusType(row.clubStatus)">{{clubStatusLabel(row.clubStatus)}}</el-tag></template></el-table-column><el-table-column label="操作" min-width="220"><template #default="{row}"><el-button link @click="router.push(`/admin/clubs/${row.clubId}`)">查看</el-button><el-button link :type="row.clubStatus==='ACTIVE'?'danger':'success'" @click="toggleClub(row)">{{row.clubStatus==='ACTIVE'?'停用俱乐部':'启用俱乐部'}}</el-button><el-button v-if="row.leaderStatus" link :type="row.leaderStatus==='ENABLED'?'danger':'success'" @click="toggleLeader(row)">{{row.leaderStatus==='ENABLED'?'停用负责人':'启用负责人'}}</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.size" :total="total" layout="total,prev,pager,next" @current-change="load"/><el-divider content-position="left">待审核俱乐部注册</el-divider><el-table :data="pending" empty-text="暂无待审核俱乐部注册"><el-table-column prop="clubApplyName" label="申请俱乐部"/><el-table-column prop="realName" label="负责人"/><el-table-column prop="phone" label="手机号"/><el-table-column label="状态"><template #default="{row}">{{accountStatusLabel(row.userStatus)}}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button link type="success" @click="approve(row)">审核通过</el-button></template></el-table-column></el-table></el-card></template>
<style scoped>h2{margin:0}.el-pagination{margin-top:16px;justify-content:flex-end}</style>
