<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage} from 'element-plus'
import {createInternalUser,getInternalUsers,updateInternalUserStatus} from '../../api/user'
import {accountStatusLabel,statusType} from '../../constants/status'
const rows=ref([]),total=ref(0),loading=ref(false),saving=ref(false),visible=ref(false),formRef=ref()
const query=reactive({username:'',roleCode:'EVENT_ADMIN',userStatus:'',page:1,size:10})
const form=reactive({roleCode:'EVENT_ADMIN',phone:'',realName:'',employeeNo:''})
const roleOptions=Object.freeze([{value:'EVENT_ADMIN',label:'赛事管理员'},{value:'ADMIN',label:'系统管理员'}])
const statusOptions=Object.freeze([{value:'PENDING_ACTIVATION',label:'待首次启用'},{value:'ENABLED',label:'已启用'},{value:'DISABLED',label:'已停用'},{value:'CANCELLED',label:'已注销'}])
const roleName=code=>code==='EVENT_ADMIN'?'赛事管理员':'系统管理员'
const prefix=computed(()=>form.roleCode==='EVENT_ADMIN'?'EA':'SA')
const rules={roleCode:[{required:true,message:'请选择管理员类型'}],phone:[{required:true,message:'请输入手机号'},{pattern:/^1\d{10}$/,message:'请输入11位手机号'}],realName:[{required:true,message:'请输入姓名'}],employeeNo:[{required:true,message:'请输入4位工号数字'},{pattern:/^\d{4}$/,message:'请输入4位工号数字'}]}
const load=async()=>{loading.value=true;try{const data=(await getInternalUsers(query)).data;rows.value=data.records;total.value=data.total}finally{loading.value=false}}
const reset=()=>{Object.assign(query,{username:'',roleCode:'EVENT_ADMIN',userStatus:'',page:1});load()}
const open=()=>{Object.assign(form,{roleCode:query.roleCode,phone:'',realName:'',employeeNo:''});visible.value=true}
const save=async()=>{await formRef.value.validate();saving.value=true;try{await createInternalUser(form);visible.value=false;ElMessage.success('预登记成功，账号待本人首次启用');query.roleCode=form.roleCode;await load()}finally{saving.value=false}}
const toggle=async row=>{if(row.userStatus==='PENDING_ACTIVATION')return ElMessage.warning('等待本人完成首次启用');if(row.userStatus==='CANCELLED')return;const next=row.userStatus==='ENABLED'?'DISABLED':'ENABLED';await updateInternalUserStatus(row.userId,next);ElMessage.success(next==='ENABLED'?'账号已重新启用':'账号已停用');await load()}
onMounted(load)
</script>
<template><el-card><template #header><div class="head"><h2>内部人员管理</h2><el-button type="primary" @click="open">新增管理账号</el-button></div></template><el-alert class="tip" type="info" :closable="false" title="预登记后状态为待首次启用；本人使用手机号和4位工号数字设置密码。"/><el-form inline><el-form-item label="姓名"><el-input v-model="query.username" clearable/></el-form-item><el-form-item label="管理员类型"><el-select v-model="query.roleCode" style="width:150px" @change="query.page=1;load()"><el-option v-for="option in roleOptions" :key="option.value" :label="option.label" :value="option.value"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="query.userStatus" style="width:145px" clearable><el-option v-for="option in statusOptions" :key="option.value" :label="option.label" :value="option.value"/></el-select></el-form-item><el-button type="primary" @click="query.page=1;load()">查询</el-button><el-button @click="reset">重置</el-button></el-form><el-table :data="rows" v-loading="loading"><el-table-column prop="realName" label="姓名"/><el-table-column prop="phone" label="手机号"/><el-table-column label="工号"><template #default="{row}">{{row.employeeNo}}</template></el-table-column><el-table-column label="类型"><template #default="{row}">{{roleName(row.roleCode)}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="statusType(row.userStatus)">{{accountStatusLabel(row.userStatus)}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="{row}"><span v-if="row.userStatus==='CANCELLED'">不可操作</span><el-button v-else link :disabled="row.userStatus==='PENDING_ACTIVATION'" :type="row.userStatus==='ENABLED'?'danger':'success'" @click="toggle(row)">{{row.userStatus==='ENABLED'?'停用':'启用'}}</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.size" :total="total" layout="total,prev,pager,next" @current-change="load"/></el-card><el-dialog v-model="visible" title="预登记管理账号" width="520px"><el-form ref="formRef" :model="form" :rules="rules" label-width="110px"><el-form-item label="管理员类型" prop="roleCode"><el-select v-model="form.roleCode"><el-option v-for="option in roleOptions" :key="option.value" :label="option.label" :value="option.value"/></el-select></el-form-item><el-form-item label="手机号" prop="phone"><el-input v-model="form.phone"/></el-form-item><el-form-item label="姓名" prop="realName"><el-input v-model="form.realName"/></el-form-item><el-form-item label="4位工号数字" prop="employeeNo"><el-input v-model="form.employeeNo" maxlength="4"><template #prepend>{{prefix}}</template></el-input></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">确认预登记</el-button></template></el-dialog></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:center}.head h2{margin:0}.tip{margin-bottom:18px}.el-form :deep(.el-select){min-width:145px}.el-pagination{margin-top:16px;justify-content:flex-end}</style>
