<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { getClubs } from '../../api/club'
import { getAdminRounds, getAdminSeasons } from '../../api/league'
import { getMatches, getStadiums, updateMatch } from '../../api/match'

const rows = ref([]), total = ref(0), seasons = ref([]), rounds = ref([]), clubs = ref([]), stadiums = ref([]), loading = ref(false), error = ref(''), visible = ref(false), saving = ref(false), editingId = ref(null), editingStatus = ref('DRAFT'), formRef = ref()
const query = reactive({ page: 1, size: 10, seasonId: null, matchStatus: '' })
const statusOptions = Object.freeze([{ value: 'DRAFT', label: '草稿' }, { value: 'PUBLISHED', label: '已发布' }, { value: 'IN_PROGRESS', label: '比赛进行中' }, { value: 'FINISHED', label: '已结束' }, { value: 'CANCELLED', label: '已取消' }])
const empty = () => ({ seasonId: null, roundId: null, homeClubId: null, awayClubId: null, stadiumId: null, matchTime: '' }), form = reactive(empty())
const rules = { seasonId: [{ required: true, message: '请选择赛季' }], roundId: [{ required: true, message: '请选择轮次' }], homeClubId: [{ required: true, message: '请选择主队' }], awayClubId: [{ required: true, message: '请选择客队' }], stadiumId: [{ required: true, message: '请选择场馆' }], matchTime: [{ required: true, message: '请选择比赛时间' }] }
const load = async () => { loading.value = true; error.value = ''; try { const result = (await getMatches(query)).data; rows.value = result.records; total.value = result.total } catch (e) { error.value = e?.message || '加载比赛失败，请稍后重试。' } finally { loading.value = false } }
const reset = () => { Object.assign(query, { page: 1, seasonId: null, matchStatus: '' }); load() }
watch(() => form.seasonId, async id => { rounds.value = id ? (await getAdminRounds(id)).data : []; if (!rounds.value.some(item => item.roundId === form.roundId)) form.roundId = null })
watch(() => form.homeClubId, id => { const club = clubs.value.find(item => item.clubId === id); if (club?.homeStadiumId) form.stadiumId = club.homeStadiumId })
const open = async row => { editingId.value = row?.matchId || null; editingStatus.value = row?.matchStatus || 'DRAFT'; Object.assign(form, empty(), row || {}); if (form.seasonId) rounds.value = (await getAdminRounds(form.seasonId)).data; visible.value = true }
const save = async () => { await formRef.value.validate(); if (form.homeClubId === form.awayClubId) return ElMessage.error('主队和客队不能相同'); saving.value = true; try { await updateMatch(editingId.value, form); visible.value = false; ElMessage.success('比赛已保存'); await load() } finally { saving.value = false } }
const initialize = async () => { loading.value = true; error.value = ''; try { const [seasonResult, clubResult, stadiumResult] = await Promise.all([getAdminSeasons(), getClubs({ page: 1, size: 100 }), getStadiums()]); seasons.value = seasonResult.data; clubs.value = clubResult.data.records; stadiums.value = stadiumResult.data.filter(item => item.stadiumStatus === 'ACTIVE'); await load() } catch (e) { error.value = e?.message || '加载比赛失败，请稍后重试。'; loading.value = false } }
onMounted(initialize)
</script>

<template>
  <div class="operations-page">
    <PageHeader :breadcrumb="[{label:'比赛执行'},{label:'比赛管理'}]" title="比赛管理" subtitle="维护比赛对阵、场馆、时间和当前执行状态。" />
    <FilterBar :model="query"><el-form-item label="赛季"><el-select v-model="query.seasonId" clearable filterable placeholder="全部赛季"><el-option v-for="seasonItem in seasons" :key="seasonItem.seasonId" :label="seasonItem.seasonName" :value="seasonItem.seasonId" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="query.matchStatus" clearable placeholder="全部状态"><el-option v-for="status in statusOptions" :key="status.value" :label="status.label" :value="status.value" /></el-select></el-form-item><template #actions><el-button @click="reset">重置</el-button><el-button type="primary" @click="query.page=1;load()">查询</el-button></template></FilterBar>
    <TableWrapper label="比赛列表">
      <DataState :loading="loading" :error="error" :empty="!rows.length" empty-title="暂无比赛" empty-description="自动排赛并确认赛程后，比赛会显示在这里；也可调整筛选条件后重新查询。" @retry="initialize">
        <el-table :data="rows"><el-table-column prop="roundName" label="轮次" min-width="110" show-overflow-tooltip /><el-table-column label="对阵" min-width="230"><template #default="{row}"><strong>{{ row.homeClubName }}</strong><span class="versus">对阵</span><strong>{{ row.awayClubName }}</strong></template></el-table-column><el-table-column label="比赛时间" min-width="180"><template #default="{row}">{{ $formatDateTime(row.matchTime) }}</template></el-table-column><el-table-column prop="stadiumName" label="场馆" min-width="150" show-overflow-tooltip /><el-table-column label="状态" width="120"><template #default="{row}"><StatusTag :value="row.matchStatus" /></template></el-table-column><el-table-column label="操作" width="180" fixed="right"><template #default="{row}"><RouterLink :to="`/admin/matches/${row.matchId}`" class="table-link">维护比赛</RouterLink><el-button v-if="['DRAFT','PUBLISHED'].includes(row.matchStatus)" link @click="open(row)">编辑</el-button></template></el-table-column></el-table>
      </DataState>
      <template #footer><el-pagination v-if="total > query.size" v-model:current-page="query.page" :page-size="query.size" :total="total" layout="total,prev,pager,next" @current-change="load" /></template>
    </TableWrapper>

    <el-dialog v-model="visible" class="app-dialog" title="编辑比赛" width="640px"><el-alert v-if="editingStatus === 'PUBLISHED'" title="已发布比赛仅允许修改比赛时间。" type="warning" :closable="false" /><el-form ref="formRef" class="match-form" :model="form" :rules="rules" label-position="top"><div class="form-grid"><el-form-item label="赛季" prop="seasonId"><el-select v-model="form.seasonId" :disabled="editingStatus === 'PUBLISHED'" filterable><el-option v-for="seasonItem in seasons" :key="seasonItem.seasonId" :label="seasonItem.seasonName" :value="seasonItem.seasonId" /></el-select></el-form-item><el-form-item label="轮次" prop="roundId"><el-select v-model="form.roundId" :disabled="editingStatus === 'PUBLISHED'"><el-option v-for="roundItem in rounds" :key="roundItem.roundId" :label="roundItem.roundName" :value="roundItem.roundId" /></el-select></el-form-item><el-form-item label="主队" prop="homeClubId"><el-select v-model="form.homeClubId" filterable :disabled="editingStatus === 'PUBLISHED'"><el-option v-for="club in clubs" :key="club.clubId" :label="club.clubName" :value="club.clubId" /></el-select></el-form-item><el-form-item label="客队" prop="awayClubId"><el-select v-model="form.awayClubId" filterable :disabled="editingStatus === 'PUBLISHED'"><el-option v-for="club in clubs" :key="club.clubId" :label="club.clubName" :value="club.clubId" /></el-select></el-form-item><el-form-item label="场馆" prop="stadiumId"><el-select v-model="form.stadiumId" :disabled="editingStatus === 'PUBLISHED'" filterable><el-option v-for="stadium in stadiums" :key="stadium.stadiumId" :label="stadium.stadiumName" :value="stadium.stadiumId" /></el-select></el-form-item><el-form-item label="比赛时间" prop="matchTime"><el-date-picker v-model="form.matchTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" aria-label="比赛时间" /></el-form-item></div></el-form><template #footer><el-button :disabled="saving" @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存比赛</el-button></template></el-dialog>
  </div>
</template>

<style scoped>.versus{margin:0 var(--space-2);color:var(--color-text-muted);font-size:var(--font-size-xs)}.table-link{margin-right:var(--space-2);color:var(--color-pitch);font-size:var(--font-size-sm);font-weight:var(--font-weight-semibold)}.table-link:hover{text-decoration:underline;text-underline-offset:3px}.match-form{margin-top:var(--space-4)}.match-form :deep(.el-select),.match-form :deep(.el-date-editor){width:100%}</style>
