<script setup>
import {onMounted,reactive,ref} from 'vue'
import {getAdminEnrollment,getAdminEnrollments} from '../../api/club'
import {formatDateTime} from '../../utils/format'
const rows=ref([]),total=ref(0),loading=ref(false),visible=ref(false),detail=ref({})
const query=reactive({seasonId:null,clubId:null,enrollmentStatus:'SUBMITTED',page:1,size:20})
const load=async()=>{loading.value=true;try{const r=(await getAdminEnrollments(query)).data;rows.value=r.records;total.value=r.total}finally{loading.value=false}}
const show=async id=>{detail.value=(await getAdminEnrollment(id)).data;visible.value=true}
onMounted(load)
</script>
<template><el-card><template #header><div class="head"><h2>赛季报名</h2><el-button @click="load">刷新</el-button></div></template><el-form inline><el-form-item label="赛季ID"><el-input-number v-model="query.seasonId" :min="1" clearable/></el-form-item><el-form-item label="俱乐部ID"><el-input-number v-model="query.clubId" :min="1" clearable/></el-form-item><el-form-item><el-button type="primary" @click="query.page=1;load()">查询</el-button></el-form-item></el-form><el-table v-loading="loading" :data="rows"><el-table-column prop="seasonName" label="赛季"/><el-table-column prop="clubName" label="俱乐部"/><el-table-column prop="stadiumName" label="主场"/><el-table-column label="报名时间"><template #default="{row}">{{formatDateTime(row.submittedAt)}}</template></el-table-column><el-table-column prop="playerCount" label="球员数"/><el-table-column prop="coachCount" label="教练数"/><el-table-column prop="enrollmentStatus" label="状态"/><el-table-column label="操作"><template #default="{row}"><el-button link @click="show(row.enrollmentId)">查看详情</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card><el-dialog v-model="visible" title="报名详情" width="800px"><el-descriptions :column="2" border><el-descriptions-item label="赛季">{{detail.seasonName}}</el-descriptions-item><el-descriptions-item label="俱乐部">{{detail.clubName}}</el-descriptions-item><el-descriptions-item label="主场">{{detail.stadiumName}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.enrollmentStatus}}</el-descriptions-item></el-descriptions><h3>球员阵容</h3><el-table :data="detail.players"><el-table-column prop="playerName" label="姓名"/><el-table-column prop="shirtNo" label="号码"/><el-table-column prop="position" label="位置"/><el-table-column prop="lineupRole" label="首发/替补"/><el-table-column prop="age" label="年龄"/></el-table><h3>教练</h3><el-table :data="detail.coaches"><el-table-column prop="coachName" label="姓名"/><el-table-column prop="title" label="职务"/></el-table></el-dialog></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:center}.head h2{margin:0}.el-pagination{margin-top:16px;justify-content:flex-end}</style>
