<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {getMatch,updateMatchScore,updateMatchStatus} from '../../api/match'
import {useSystemTimeStore} from '../../stores/systemTime'
const route=useRoute(),router=useRouter(),match=ref({}),loading=ref(false),scoreVisible=ref(false),scoreRef=ref(),score=reactive({homeScore:0,awayScore:0})
const systemTimeStore=useSystemTimeStore()
const scoreRules={homeScore:[{required:true,type:'number',min:0,message:'比分不得小于0'}],awayScore:[{required:true,type:'number',min:0,message:'比分不得小于0'}]}
const actions=computed(()=>({DRAFT:[['PUBLISHED','发布'],['CANCELLED','取消']],PUBLISHED:[['IN_PROGRESS','开始'],['CANCELLED','取消']],IN_PROGRESS:[['FINISHED','结束'],['CANCELLED','取消']]}[match.value.matchStatus]||[]))
const load=async()=>{loading.value=true;try{match.value=(await getMatch(route.params.id)).data}finally{loading.value=false}}
const transition=async(status,label)=>{await ElMessageBox.confirm(`确认${label}该比赛？`,'状态确认');await updateMatchStatus(match.value.matchId,status);systemTimeStore.notifyBusinessChange();ElMessage.success('状态已更新');await load()}
const openScore=()=>{score.homeScore=match.value.homeScore??0;score.awayScore=match.value.awayScore??0;scoreVisible.value=true}
const saveScore=async()=>{await scoreRef.value.validate();await updateMatchScore(match.value.matchId,score);systemTimeStore.notifyBusinessChange();scoreVisible.value=false;ElMessage.success(match.value.matchStatus==='FINISHED'?'比分已更正，积分榜已重算':'比分已保存，请完成比赛状态以更新积分榜');await load()}
onMounted(load)
</script>
<template><el-card v-loading="loading"><template #header><div class="head"><el-page-header @back="router.push('/admin/matches')"><template #content>比赛维护</template></el-page-header><div><el-button type="warning" @click="router.push(`/admin/matches/${match.matchId}/tickets`)">票务配置</el-button><el-button v-for="a in actions" :key="a[0]" :type="a[0]==='CANCELLED'?'danger':'primary'" @click="transition(a[0],a[1])">{{a[1]}}</el-button><el-button v-if="['IN_PROGRESS','FINISHED'].includes(match.matchStatus)" type="success" @click="openScore">{{match.matchStatus==='FINISHED'?'更正比分':'录入比分'}}</el-button></div></div></template><div class="fixture"><h2>{{match.homeClubName}}</h2><strong>{{match.homeScore==null?'VS':`${match.homeScore} : ${match.awayScore}`}}</strong><h2>{{match.awayClubName}}</h2></div><el-descriptions :column="2" border><el-descriptions-item label="赛季">{{match.seasonName}}</el-descriptions-item><el-descriptions-item label="轮次">{{match.roundName}}</el-descriptions-item><el-descriptions-item label="比赛时间">{{match.matchTime}}</el-descriptions-item><el-descriptions-item label="比赛场馆">{{match.stadiumName}}</el-descriptions-item><el-descriptions-item label="状态">{{match.matchStatus}}</el-descriptions-item><el-descriptions-item label="首次发布">{{match.publishedAt||'尚未发布'}}</el-descriptions-item></el-descriptions></el-card><el-dialog v-model="scoreVisible" title="比分维护" width="420px"><el-form ref="scoreRef" :model="score" :rules="scoreRules" label-width="100px"><el-form-item :label="match.homeClubName" prop="homeScore"><el-input-number v-model="score.homeScore" :min="0"/></el-form-item><el-form-item :label="match.awayClubName" prop="awayScore"><el-input-number v-model="score.awayScore" :min="0"/></el-form-item></el-form><template #footer><el-button @click="scoreVisible=false">取消</el-button><el-button type="primary" @click="saveScore">保存</el-button></template></el-dialog></template>
<style scoped>.head{display:flex;align-items:center;justify-content:space-between}.fixture{display:grid;grid-template-columns:1fr 140px 1fr;align-items:center;text-align:center;margin:30px}.fixture strong{font-size:30px}</style>
