<script setup>
import {onMounted,reactive,ref} from 'vue'
import {ElMessage} from 'element-plus'
import {confirmSchedule,getSchedule,getSchedules} from '../../api/league'
import {formatDateTime} from '../../utils/format'
const rows=ref([]),total=ref(0),loading=ref(false),visible=ref(false),detail=ref({})
const query=reactive({seasonId:null,batchStatus:'',page:1,size:20})
const load=async()=>{loading.value=true;try{const r=(await getSchedules(query)).data;rows.value=r.records;total.value=r.total}finally{loading.value=false}}
const show=async row=>{detail.value=(await getSchedule(row.seasonId)).data;visible.value=true}
const confirm=async()=>{detail.value=(await confirmSchedule(detail.value.seasonId)).data;ElMessage.success('赛程已确认');await load()}
onMounted(load)
</script>
<template><el-card><template #header><div class="head"><h2>赛程管理</h2><el-button @click="load">刷新</el-button></div></template><el-form inline><el-form-item label="赛季ID"><el-input-number v-model="query.seasonId" :min="1" clearable/></el-form-item><el-form-item label="状态"><el-select v-model="query.batchStatus" clearable style="width:150px"><el-option label="待确认" value="GENERATED"/><el-option label="已确认" value="CONFIRMED"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="query.page=1;load()">查询</el-button></el-form-item></el-form><el-table v-loading="loading" :data="rows"><el-table-column prop="seasonName" label="赛季"/><el-table-column prop="clubCount" label="球队数"/><el-table-column prop="roundCount" label="轮次"/><el-table-column prop="matchCount" label="比赛数"/><el-table-column prop="triggerType" label="生成方式"/><el-table-column label="生成时间"><template #default="{row}">{{formatDateTime(row.generatedAt)}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.batchStatus==='CONFIRMED'?'success':'warning'">{{row.batchStatus==='CONFIRMED'?'已确认':'待确认'}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button link @click="show(row)">查看赛程</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card><el-dialog v-model="visible" title="赛程详情" width="900px"><el-descriptions :column="3" border><el-descriptions-item label="赛季">{{detail.seasonName}}</el-descriptions-item><el-descriptions-item label="球队/轮次/比赛">{{detail.clubCount}} / {{detail.roundCount}} / {{detail.matchCount}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.batchStatus}}</el-descriptions-item></el-descriptions><section v-for="round in detail.rounds||[]" :key="round.roundNo"><h3>第{{round.roundNo}}轮</h3><el-table :data="round.matches"><el-table-column label="时间"><template #default="{row}">{{formatDateTime(row.matchDateTime)}}</template></el-table-column><el-table-column prop="homeClubName" label="主队"/><el-table-column prop="awayClubName" label="客队"/><el-table-column prop="stadiumName" label="主场"/><el-table-column prop="matchStatus" label="比赛状态"/></el-table></section><template #footer><el-button @click="visible=false">关闭</el-button><el-button v-if="detail.batchStatus==='GENERATED'" type="primary" @click="confirm">确认赛程</el-button></template></el-dialog></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:center}.head h2{margin:0}.el-pagination{margin-top:16px;justify-content:flex-end}h3{margin:20px 0 8px}</style>
